// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _bf_h_
#define _bf_h_

#include <list>
#include <string>
#include <staff/common/DataObject.h>
#include <staff/common/WsdlTypes.h>
#include <staff/common/Optional.h>
#include <staff/common/Attribute.h>
#include "ws_addr.h"
#include "xml.h"

// *interface.attributeFormDefault: unqualified
// *interface.elementFormDefault: qualified
// *interface.targetNamespace: http://docs.oasis-open.org/wsrf/bf-2

  struct BaseFaultType;

  typedef std::string Description;

  struct BaseFaultType
  {
    struct ErrorCode
    {
      // *useParentElement: true
      staff::anyType tParent;
      // *isAttribute: true
      staff::anyURI dialect;
    };

    struct FaultCause
    {
      // *useParentElement: true
      staff::DataObject tUnnamed0;
    };

    // *useParentElement: true
    std::list<staff::DataObject> tUnnamed0;
    staff::dateTime Timestamp;
    staff::Optional< ::EndpointReferenceType > Originator;
    staff::Optional<struct ::BaseFaultType::ErrorCode> ErrorCode;
    // *useParentElement: true
    std::list< ::Description > Description;
    staff::Optional<struct ::BaseFaultType::FaultCause> FaultCause;
    staff::anyAttribute lsAnyAttributes;
  };


#endif // _bf_h_

