// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _bfProxy_h_
#define _bfProxy_h_

#include "bf.h"
#include "ws_addrProxy.h"
#include "xmlProxy.h"

namespace staff
{
  class DataObject;
  DataObject& operator<<(DataObject& rdoParam, const struct ::BaseFaultType& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::BaseFaultType& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::BaseFaultType::ErrorCode& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::BaseFaultType::ErrorCode& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::BaseFaultType::FaultCause& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::BaseFaultType::FaultCause& rstStruct);
  DataObject& SerializeTypedef_Description(DataObject& rdoParam, const ::Description& rtType);
  const DataObject& DeserializeTypedef_Description(const DataObject& rdoParam, ::Description& rtType);
}

#endif

