// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _includeProxy_h_
#define _includeProxy_h_

#include "include.h"

namespace staff
{
  class DataObject;
  DataObject& operator<<(DataObject& rdoParam, const struct ::Include& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::Include& rstStruct);
}

#endif

