// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _include_h_
#define _include_h_

#include <list>
#include <staff/common/DataObject.h>
#include <staff/common/WsdlTypes.h>
#include <staff/common/Attribute.h>

// *interface.targetNamespace: http://www.w3.org/2004/08/xop/include

  struct Include;

  struct Include
  {
    // *useParentElement: true
    std::list<staff::DataObject> tUnnamed0;
    staff::anyAttribute lsAnyAttributes;
    // *isAttribute: true
    staff::anyURI href;
  };


#endif // _include_h_

