// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _Proxy_h_
#define _Proxy_h_

#include ".h"

namespace staff
{
  class DataObject;
  DataObject& operator<<(DataObject& rdoParam, const struct ::Body& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::Body& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::Envelope& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::Envelope& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::Header& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::Header& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::Fault& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::Fault& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::detail& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::detail& rstStruct);
  DataObject& SerializeTypedef_encodingStyle(DataObject& rdoParam, const ::encodingStyle& rtType);
  const DataObject& DeserializeTypedef_encodingStyle(const DataObject& rdoParam, ::encodingStyle& rtType);
}

#endif

