// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _ws_addrProxy_h_
#define _ws_addrProxy_h_

#include "ws_addr.h"

namespace staff
{
  class DataObject;
  DataObject& operator<<(DataObject& rdoParam, const ::RelationshipType eEnumValue);
  const DataObject& operator>>(const DataObject& rdoParam, ::RelationshipType& reEnumValue);
  std::string& operator<<(std::string& sResult, const ::RelationshipType eEnumValue);
  const std::string& operator>>(const std::string& sParam, ::RelationshipType& reEnumValue);
  DataObject& operator<<(DataObject& rdoParam, const ::FaultCodesType eEnumValue);
  const DataObject& operator>>(const DataObject& rdoParam, ::FaultCodesType& reEnumValue);
  std::string& operator<<(std::string& sResult, const ::FaultCodesType eEnumValue);
  const std::string& operator>>(const std::string& sParam, ::FaultCodesType& reEnumValue);
  DataObject& operator<<(DataObject& rdoParam, const struct ::EndpointReferenceType& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::EndpointReferenceType& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::ReferenceParametersType& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::ReferenceParametersType& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::MetadataType& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::MetadataType& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::RelatesToType& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::RelatesToType& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::AttributedAnyType& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::AttributedAnyType& rstStruct);
  DataObject& operator<<(DataObject& rdoParam, const struct ::ProblemActionType& rstStruct);
  const DataObject& operator>>(const DataObject& rdoParam, struct ::ProblemActionType& rstStruct);
  DataObject& SerializeTypedef_RelationshipTypeOpenEnum(DataObject& rdoParam, const ::RelationshipTypeOpenEnum& rtType);
  const DataObject& DeserializeTypedef_RelationshipTypeOpenEnum(const DataObject& rdoParam, ::RelationshipTypeOpenEnum& rtType);
  DataObject& SerializeTypedef_FaultCodesOpenEnumType(DataObject& rdoParam, const ::FaultCodesOpenEnumType& rtType);
  const DataObject& DeserializeTypedef_FaultCodesOpenEnumType(const DataObject& rdoParam, ::FaultCodesOpenEnumType& rtType);
  DataObject& SerializeTypedef_AttributedURIType(DataObject& rdoParam, const ::AttributedURIType& rtType);
  const DataObject& DeserializeTypedef_AttributedURIType(const DataObject& rdoParam, ::AttributedURIType& rtType);
  DataObject& SerializeTypedef_AttributedUnsignedLongType(DataObject& rdoParam, const ::AttributedUnsignedLongType& rtType);
  const DataObject& DeserializeTypedef_AttributedUnsignedLongType(const DataObject& rdoParam, ::AttributedUnsignedLongType& rtType);
  DataObject& SerializeTypedef_AttributedQNameType(DataObject& rdoParam, const ::AttributedQNameType& rtType);
  const DataObject& DeserializeTypedef_AttributedQNameType(const DataObject& rdoParam, ::AttributedQNameType& rtType);
}

#endif

