// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _xml_h_
#define _xml_h_


// *interface.targetNamespace: http://www.w3.org/XML/1998/namespace
// *interface.lang: en

#endif // _xml_h_

