// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _xmlmimeProxy_h_
#define _xmlmimeProxy_h_

#include "xmlmime.h"

namespace staff
{
  class DataObject;
  DataObject& SerializeTypedef_base64Binary(DataObject& rdoParam, const ::base64Binary& rtType);
  const DataObject& DeserializeTypedef_base64Binary(const DataObject& rdoParam, ::base64Binary& rtType);
  DataObject& SerializeTypedef_hexBinary(DataObject& rdoParam, const ::hexBinary& rtType);
  const DataObject& DeserializeTypedef_hexBinary(const DataObject& rdoParam, ::hexBinary& rtType);
}

#endif

