// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/

#ifndef _xmlmime_h_
#define _xmlmime_h_

#include <staff/common/WsdlTypes.h>
#include <staff/utils/Base64Binary.h>
#include <staff/utils/HexBinary.h>

// *interface.targetNamespace: http://www.w3.org/2005/05/xmlmime
  typedef staff::base64Binary base64Binary;
  typedef staff::hexBinary hexBinary;


#endif // _xmlmime_h_

