// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#include <staff/utils/fromstring.h>
#include <staff/utils/tostring.h>
#include <staff/utils/HexBinary.h>
#include <staff/utils/Base64Binary.h>
#include <staff/common/DataObject.h>
#include <staff/common/Attribute.h>
#include "xmlmimeProxy.h"

namespace staff
{
///////////////////////////////////////////////////////////////////////////////////////////////////////
// typedef serializators

DataObject& SerializeTypedef_base64Binary(DataObject& rdoParam, const ::base64Binary& rtType)
{
  rdoParam.SetValue(rtType);
  rdoParam.SetNamespaceUriGenPrefix("http://www.w3.org/2005/05/xmlmime", true);
  return rdoParam;
}


DataObject& SerializeTypedef_hexBinary(DataObject& rdoParam, const ::hexBinary& rtType)
{
  rdoParam.SetValue(rtType);
  rdoParam.SetNamespaceUriGenPrefix("http://www.w3.org/2005/05/xmlmime", true);
  return rdoParam;
}


///////////////////////////////////////////////////////////////////////////////////////////////////////
// typedef deserializators
const DataObject& DeserializeTypedef_base64Binary(const DataObject& rdoParam, ::base64Binary& rtType)
{
  rdoParam.GetValue(rtType);
  return rdoParam;
}

const DataObject& DeserializeTypedef_hexBinary(const DataObject& rdoParam, ::hexBinary& rtType)
{
  rdoParam.GetValue(rtType);
  return rdoParam;
}

}


