// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _xmlProxy_h_
#define _xmlProxy_h_

#include "xml.h"

namespace staff
{
  class DataObject;
}

#endif

